---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/employees":
    get:
      summary: list employees
      responses:
        '200':
          description: successful
    post:
      summary: create employee
      responses:
        '200':
          description: successful
  "/employees/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show employee
      responses:
        '200':
          description: successful
    patch:
      summary: update employee
      responses:
        '200':
          description: successful
    put:
      summary: update employee
      responses:
        '200':
          description: successful
    delete:
      summary: delete employee
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
